### ISSUE TITLE
node(sys) is deprecated. Use util instead.

### ISSUE THREAD

**Issue by nileshprasad** [RIAEvangelist/node-cmd#1]
This might be causing node-cmd is unable to open a node file. Maybe?

**Comment by RIAEvangelist** [comment]
I doubt it is effecting running a file, but will upgrade the code.

**Comment by nileshprasad** [comment]
Yes, you are correct. It does not effect running the files. I was able to open multiple files successfully.

**Comment by RIAEvangelist** [comment]
This had no effect on the files. The user was using the wrong path.
