### ISSUE TITLE
Unable to change directory.

### ISSUE THREAD

**Issue by phuwin1995** [RIAEvangelist/node-cmd#10]
I have these lines of codes:

```
var dir = '/var/www/html/superprojectexperimental/' + projectName;
cmd.run('mkdir -p '+ dir);
cmd.run('cd ' + dir);
cmd.get('pwd',function(data){
    console.log('the current working dir is : ',data);
    }
);  
```

The `data` printed is only `/`
The `mkdir -p` works pretty well.

**Comment by RIAEvangelist** [comment]
Each one of your commands runs in a separate terminal.

Try a template string, like :

``` javascript

cmd.get(
    ` cd my folder
    ls
    touch hello.txt
    ls
    `
)

```

**Comment by samthomson** [comment]
@phuwin are you on windows? If so you must run commands as one line. See my comment on issue #18
