### ISSUE TITLE
Multi-line commands not working

### ISSUE THREAD

**Issue by stephen-last** [RIAEvangelist/node-cmd#18]
I see you have an example using multiple lines, which looks really useful.

```js
cmd.get(
  `
    git clone https://github.com/RIAEvangelist/node-cmd.git
    cd node-cmd
    ls
  `, function(data, err, stderr){}
)
```

I can't seem to get this to work:

```js
// works!
cmd.get(`node -v`, function (data, err, stderr) {
  if (err) {
    console.log('cmd err ===', err)
  } else {
    if (stderr) { console.log('cmd stderr ===', stderr) }
    console.log('cmd data ===', data) // cmd data === v4.2.2
  }
})

// doesn't work!!
cmd.get(`
  node -v
  `, function (data, err, stderr) {
  if (err) {
    console.log('cmd err ===', err)
  } else {
    if (stderr) { console.log('cmd stderr ===', stderr) }
    console.log('cmd data ===', data) // cmd data ===
  }
})
```

I'm not getting any errors (from `err` or `stderr`), but `data` is an empty string as soon as I make the template string multi-line.

What am I doing wrong..?

**Comment by RIAEvangelist** [comment]
perhaps its the spaces? Not sure what OS you are on.

**Comment by stephen-last** [comment]
Windows.

Have you tried the multi-line example on Windows..?

**Comment by RIAEvangelist** [comment]
Have you tried without the leading spaces and line breaks? Or by using the standard multi command pattern on windows. Linux, unix and mac support multiline commands by default. Perhaps windows does not? This is using only whatever is supported in the OS.

**Comment by samthomson** [comment]
@stephen-last I had the same issue as you on windows. I had to modify the commands. On Windows you specify all commands on one line, separating them with ampersand.

```
cmd.get(
  `git clone https://github.com/RIAEvangelist/node-cmd.git & cd node-cmd & ls`, 
  function(data, err, stderr){}
)
```

**Comment by stephen-last** [comment]
@samthomson That's what I ended up doing when using `node-cmd`.

I've also written my own version: [cmd-promise](https://github.com/stephen-last/cmd-promise).

This version handles multiple lines on Windows, although I've not tested on any other OS's.

**Comment by codexu** [comment]
``` javascript
const os = require('os');
const cmd = require('node-cmd');

function nodeCmdOs(arr) {
  return new Promise((resolve, reject) => {
    let cmdStr = '';
    if(os.type() === 'Windows_NT') {
      arr.forEach((item, index) => {
        index === 0 ? cmdStr += item : cmdStr = cmdStr + ' & ' + item
      });
    } else {
      arr.forEach((item, index) => {
        index === 0 ? cmdStr += item : cmdStr = cmdStr + '\n' + item
      });
    }
    cmd.get(cmdStr, function (err, data, stderr) {
        if (!err) {
          resolve()
        } else {
          reject(err)
        }
      }
    );
  })
}

exports = module.exports = nodeCmdOs;
```
