### ISSUE TITLE
Err first standard

### ISSUE THREAD

**Issue by stephen-last** [RIAEvangelist/node-cmd#19]
I'd like to use [Bluebirds `Promise.promisify`](http://bluebirdjs.com/docs/api/promise.promisify.html).

```js
import Promise from 'bluebird'
import cmd from 'node-cmd'

const getAsync = Promise.promisify(cmd.get, { multiArgs: true, context: cmd })

getAsync('node -v').then(data => {
  console.log('cmd data', data)
}).catch(err => {
  console.log('cmd err', err)
})
```

This fails I think, because `node-cmd` doesn't use the [standard node error-first pattern](https://nodejs.org/api/errors.html#errors_node_js_style_callbacks) which Bluebird wants:

> The node function should conform to node.js convention of accepting a callback as last argument and calling that callback with error as the first argument and success value on the second argument.

The above code calls `catch` but actually displays the contents of `data`.

Any plans to switch to standard node-style error-first callbacks..?

**Comment by RIAEvangelist** [comment]
sounds reasonable, could you make a PR with the updates for error first?

**Comment by stephen-last** [comment]
**Notice** - this is my first time forking, cloning and submitting a pull request on Github, so if I'm not doing something right please do point me in the right direction.

I've submitted a pull request with a change to the code and readme, in a new branch.

How does it look..?

This is a breaking change, so I guess you'd need to bump the version to a new major version (3.0.0), and maybe mention the breaking change in the readme when going from v2 to v3 (I've not added this).

**Comment by RIAEvangelist** [comment]
Why is it breaking?

**Comment by RIAEvangelist** [comment]
nvm

**Comment by stephen-last** [comment]
I thought this would be a breaking change because it changes the `node-cmd` API. Anyone currently using it will have written their code to expect `data` as the first param. After this PR `err` will be the first param.

If someone is currently using `node-cmd` with `data` as the first param, then they update `node-cmd` (to the version with `err` as the first param) their code will not work as expected.

From what I understand of `semver`, API breaking changes should be major updates.

Not sure why you commented with "nvm"..?

**Comment by RIAEvangelist** [comment]
the nvm was because I realised I made a dumb comment. It was obvious why it was breaking once I looked.

**Comment by RIAEvangelist** [comment]
merged and released. Thank you :)
