### ISSUE TITLE
How do I execute multiple commands in the same context?

### ISSUE THREAD

**Issue by bronzer09** [RIAEvangelist/node-cmd#2]
I worked with git through this module, but unfortanetely I can't change the directory or to create the file.

var cmd=require('node-cmd');
var readline = require('readline');
var repository;

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question("Enter adress: ", function(address) {
    repository = address.slice(address.lastIndexOf('/')+1, address.length);
    cmd.run('git clone '+ address); 
    console.log(repository); //here starts the probem

```
cmd.run('cd ' + repository);
cmd.run('git log');
cmd.run('dir');
console.log('ok'); // ok works
rl.close();
```

});

**Comment by RIAEvangelist** [comment]
See if this helps you out :

``` javascript

var cmd=require('node-cmd');
var readline = require('readline');
var repository;

var rl = readline.createInterface(
    {
        input: process.stdin,
        output: process.stdout
    }
);

rl.question(
    "Enter adress: ", 
    function(address) {
        repository = address.slice(address.lastIndexOf('/')+1, address.length);
        console.log(repository); 
        var commands=`git clone ${address}
cd ${repository}
git log
dir`;

        console.log(commands); //see if this is what you expect

        cmd.get(
            commands,
            function(data){
                console.log('the output is :\n\n',data)
            }
        );
    }
);
```

**Comment by RIAEvangelist** [comment]
My guess is that it should work just as I wrote it it there if you copy and paste it unless your code has an issue somewhere.

**Comment by bronzer09** [comment]
thank you, if there is any instroction to use it?

2016-01-10 16:05 GMT+02:00 Brandon Nozaki Miller notifications@github.com:

**Comment by RIAEvangelist** [comment]
To use what? node-cmd? It allows you to execute command line code. If you want to execute more than one line at a time you will have to put them all into one command.

Is that what you are asking?

**Comment by bronzer09** [comment]
I just asking about what you adviced me before with that "$".

2016-01-10 22:47 GMT+02:00 Brandon Nozaki Miller notifications@github.com:

**Comment by bronzer09** [comment]
I mean what the difference beetwen standart writing the code and that one?
How does it work?

2016-01-10 16:19 GMT+02:00 Александр Бондаренко bronzer2010@gmail.com:

**Comment by RIAEvangelist** [comment]
Its called a template string and it is a part of ES6. It is built into JavaScript now. And it is AWESOME!

notice I did not use quotes. I used a back tic ->   `   <- not a  '  or a  "  

``` javascript

//using a back tics
let a = 123;
let b = `a is : ${a}`;
console.log(a);

```

your console will log `a is : 123`

``` javascript

//using regular quotes
let a = 123;
let b = 'a is : ${a}';
console.log(a);

```

your console will log `a is : ${a}`

Check out the documentation on MDN : [Template strings - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings)

**Comment by bronzer09** [comment]
Thanks, because i haven't learned ES6 yet)

2016-01-11 11:59 GMT+02:00 Brandon Nozaki Miller notifications@github.com:

**Comment by RIAEvangelist** [comment]
a lot is supported now in node v4.x, I highly recommend it.
