### ISSUE TITLE
Console output is coming as null

### ISSUE THREAD

**Issue by kuhu19** [RIAEvangelist/node-cmd#21]
Hello,
I tried using this package for running some command line commands. The command are running as far as I can tell because I see the task is done but I am unable to see the output which is printed as null.

`var testNodeCmd = function(){
    cmd.get(
        'dir',
        function(data,err,stderr){
            console.log(data);
        }
    );
}`

`testNodeCmd();`
The output for this is coming as null.

**Comment by RIAEvangelist** [comment]
What does your code look like?

**Comment by kuhu19** [comment]
I posted code also in above message. I am not sure why you're not able to see it. Anyways, posting here again:

var testNodeCmd = function(){ cmd.get( 'dir', function(data,err,stderr){ console.log(data); } ); }

testNodeCmd();

**Comment by RIAEvangelist** [comment]
If you are using the latest code it is err first in the callback.

**Comment by kuhu19** [comment]
Yes, this was the issue. I think I was using the old version previously but updated later. Thank you for your help! :) One more question I have over here. Does the package support some option to see running output?

**Comment by RIAEvangelist** [comment]
https://github.com/RIAEvangelist/node-cmd/blob/master/example/nodePythonTerminal.js
