### ISSUE TITLE
Question interfacing the console

### ISSUE THREAD

**Issue by EricBalingit** [RIAEvangelist/node-cmd#22]
Pardon my ignorance on this topic, but I am assuming that this would not handle pauses, prompts etc. in the terminal?

My objective is actually to interface with the Octave command line.  Have you ever tried anything like that, Octave or other command line software?

Is this piggybacking the standard io stream?

If you find my question insulting please accept my apology and note that I intend to get off my ass and try this, just haven't the time today. :D

**Comment by RIAEvangelist** [comment]
This is actually supported. It is in the docs and the examples folder too, the example is interacting with the python commandline.

Let me know if that does or does not get you going!

Best of luck!

**Comment by EricBalingit** [comment]
Wow, didn't realize this was such a simple wrapper.  I need to see how the octave console behaves, but this does give me a good starting point.

Really need to learn more about node.

Thanks very much!  If I find anything out of ordinary I'll reopen this. ;-)
