### ISSUE TITLE
Running cmd.get generates maxBuffer limit error

### ISSUE THREAD

**Issue by L1qu1d1c3** [RIAEvangelist/node-cmd#26]
I tried executing a cmd.get command and i get a stdOut maxBuffer exceeded error. My cmd executes a .exe file that is basically a cmd that generates output and this should be displayed on screen, but if it generates an exception, the message is quite long, so I guess that this is why I get this problem. Is there any way to modify the cmd.get method to accept a maxbuffer as optional params?

**Comment by RIAEvangelist** [comment]
this is a tricky one it would require splitting the output up. Perhaps the python example would provide some help?

https://github.com/RIAEvangelist/node-cmd/blob/master/example/nodePythonTerminal.js

**Comment by adamlubek** [comment]
I just run into the same problem, is there a plan to implement solution for that or do I need to look for another package?

**Comment by Unisolve** [comment]
Same problem here. Would love a way to be able to configure node-cmd with a larger buffer value.

**Comment by js-acevedo10** [comment]
Guys, just do it the way @RIAEvangelist says on his comment. For example, in my case I'm running Android unit tests with Graddle:

```javascript
    let buildRef = cmd.get(`
        cd ${androidStudioPath}
        ./gradlew test --stacktrace
    `);
    let unitRefData = '';
    let unitRefError = '';

    unitRef.stderr.on('data', function (data) {
        unitRefError += data;
    });

    unitRef.stdout.on('data', function (data) {
        unitRefData += data;
    });

    unitRef.stdout.on('close', function () {
        if (unitRefData.includes('BUILD SUCCESSFUL')) {
            console.log('Output:', unitRefData);
        } else {
            console.log('Output:', unitRefError);
        }
    });
```
