### ISSUE TITLE
Error changing the LAN Proxy Settings in on Windows 7

### ISSUE THREAD

**Issue by vinceprofeta** [RIAEvangelist/node-cmd#30]
Im trying to change the LAN Proxy Settings on Windows 7 through CMD from within NODE but am getting the following error.

Ive tried a few different libraries as well as use child process to run it but no luck. It works fine when I just run the command in CMD, but when running through node, I havent had any luck? ideas?

`command failed reg add /? for usage - invalid key name`

```reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings" /v ProxyServer /t REG_SZ /d 192.168.1.1:8080 /f```

*note proxy is fake in this example

**Comment by RIAEvangelist** [comment]
may need to escape the  \ ?
