### ISSUE TITLE
why will my command not execute?

### ISSUE THREAD

**Issue by wannesdemaeght** [RIAEvangelist/node-cmd#31]
```
const cmd = require('node-cmd');
cmd.run('start node c:\Trader\Logic\ok.js');

```
it opens a new cmd window and shuts it immediately.
content of ok.js is an interval every second to log "ok", so it's not like the new cmd window gets closed because the js is finished.

running 'start node c:\Trader\Logic\ok.js' in cmd does what it's supposed to do.

Any idea why it won't work from javascript?

**Comment by hansena** [comment]
You don't need "start" in your argument, try just
```javascript
const cmd = require('node-cmd');
cmd.run('node c:\Trader\Logic\ok.js');
```
