### ISSUE TITLE
Get cmd's response in error condition

### ISSUE THREAD

**Issue by lance-shi** [RIAEvangelist/node-cmd#32]
I am trying to get cmd's response in both success and error conditions. I am having the following code: 

```
const cmd = require('node-cmd');
const Promise = require('bluebird');

const getAsync = Promise.promisify(cmd.get, { multiArgs: true, context: cmd });

getAsync('sfdx force:source:status --json').then(data => {
    console.log('success');
    console.dir(data);
}).catch(err => {
    console.log('error');
    console.log(err.message);
});
```

I am trying to get the json output in error conditions as well. However, when error happens, it is hard to retrieve that. Any idea about how to walk around this issue?

**Comment by RIAEvangelist** [comment]
is it not in the data param?

I see you logged err but not data in the err scenario
