### ISSUE TITLE
The second command not getting executed in Windows

### ISSUE THREAD

**Issue by lance-shi** [RIAEvangelist/node-cmd#33]
I have tried the following code: 

```
const cmd = require('node-cmd');

let directory = "C:\\Lance\\devhub\\UkWorkflow";
cmd.get(
    `cd ${directory}
    sfdx force:source:convert -d outputTmp/ --json`,
    function(err, data, stderr) {
        if(!err) {
        	console.log("data is: ");
            console.log(data);
        } else {
        	console.log("Error!");
            console.log(stderr);
        }
    }
);
```

It seems to me that second command - sfdx not getting executed at all. Any ideas about why this is happening?

**Comment by wplittle** [comment]
With the caveat that I've not tried to run your code myself, I'm wondering
if the command interpreter is not seeing the newline in your command
string.

Try putting an & in between the two commands and see if that helps:

`cd ${directory} & sfdx force:source:convert -d outputTmp/ --json`

**Comment by Kaushal28** [comment]
Same problem here.

**Comment by RIAEvangelist** [comment]
Its the space at the beginning.

```
     get(`
        cd
        dir
    `);

```

will fail on windows because it cares about the space from the start of the line to the first char.

on windws you have to do like this :

```
     get(`
cd
dir
    `);

```

I added a windows specific example to help clarify this for people.
