### ISSUE TITLE
How to use this to open an exe (Which is a CLI tool) and then fire commands

### ISSUE THREAD

**Issue by gkvappium** [RIAEvangelist/node-cmd#35]
I have a scenario in my mobile automation framework (Typescript based) wherein I have to open an exe which is a command line interface tool and then type the commands

This CLI basically connects to a USB device. I fire commands to get certain values from the connected USB device (Example USB_HID_GetType which returns the HID)

I want to chain the commands of opening this exe and firing a command to get some value from the connected USB. 

@RIAEvangelist any thoughts or inputs

**Comment by RIAEvangelist** [comment]
Should work just fine, check the python terminal example, sounds just like what you are describing.
