### ISSUE TITLE
How to execute commands with ZSH environment

### ISSUE THREAD

**Issue by luispereira** [RIAEvangelist/node-cmd#38]
Hi, I'm trying to execute several commands but instead of /bin/sh I wanted to execute with zsh environment... 

I tried to use `source ~/.zshrc` but without success, can someone help me over here?

```
 var command= "textScriptInZsh"
      cmd.get(`
          source ~/.zshrc
          ${command}
      `, 
      function(err, data, stderr){
        if (!err) {
          console.log('Test done...\n\n',data)
        } else {
          console.log('error', err)
        }
```

**Comment by RIAEvangelist** [comment]
I do not think this is possible. If you find a way, please commit it. Currently we are just using the systems internal terminal.
