### ISSUE TITLE
Not Calling Function Callback

### ISSUE THREAD

**Issue by jtsmedley** [RIAEvangelist/node-cmd#39]
I have a set of code that the callback doesn't get called on and I suspect it is because of NMCLI using the host of my docker containers DBUS connection.

`    cmdTextFinal = 'export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket\n' + cmdText.join('\n');

    console.log(cmdTextFinal);
    cmd.get(cmdTextFinal), function(err, data, stderr){
      if (!err) {
        console.log('Applied Settings for Network');
      } else {
        console.log('Error: ' + err);
      }
      console.log('I ran');
    }`

**Comment by RIAEvangelist** [comment]
I have never seen a callback just be ignored before this is interesting.
