### ISSUE TITLE
它可以支持什么系统？ It can support the kind of system ?

### ISSUE THREAD

**Issue by jincdream** [RIAEvangelist/node-cmd#4]

**Comment by RIAEvangelist** [comment]
它支持所有的系統。
It supports all systems.

寫下你想要的系統的命令。
Write the commands for the system you want. 

使用操作系統，如果要檢測用戶系統。在項目中處理用戶類型，如果你想。
Use OS to detect the user system if you want. in your project handle the user type, if you want to.

**Comment by jincdream** [comment]
ok~ thx
