### ISSUE TITLE
How to get stderr when using promises

### ISSUE THREAD

**Issue by Coriou** [RIAEvangelist/node-cmd#42]
Hey, I'm having an issue debugging failing commands.

I'm using Bluebird to promisify `cmd.get()` (as suggested in the examples) but it seems that the "multiArgs" param only cares about when the promise resolves without errors.

I can't see to be able to get "stderr" from the `catch()` method which would be super useful to see what actually failed.

Is it something that can be done ?

**Comment by RIAEvangelist** [comment]
It might be possible, if you add it in I would merge it.
