### ISSUE TITLE
returns data missing

### ISSUE THREAD

**Issue by ruomuc** [RIAEvangelist/node-cmd#44]
Hello, today when I use the 'qrsctl' tool, I use a cmd command: "qrsctl listprefix bucktname '' ", it should return:
' market:
Aaaaa
Bbbbb '
But the data in the script returns only:
'market:
'
I make sure that the execution is correct when executed on the command line. I could not understand.

**Comment by RIAEvangelist** [comment]
I would need more info to help you.
