### ISSUE TITLE
compgen -c is the only command that does not produce output

### ISSUE THREAD

**Issue by dizid** [RIAEvangelist/node-cmd#45]
node-cmd works fine for dozens of commands, except for the 'compgen-c'
command which returns an error: stderr returns: /bin/sh: 1: compgen: not found
err returns: {"killed":false,"code":127,"signal":null,"cmd":"compgen -c"}

This is my code:

```
router.get('/commands', (req, res) => {
cmd.get('compgen -c',function(err, data, stderr) 
{res.send(data)}
```

Expected output: a list of all Linux commands on my Lubuntu box.
Now, if i run 'compgen -c' in the terminal, it executes fine and outputs all 2227 Linux commands. Linux error code 127 means (as far as i know) "Command not found". The above code works flawless with other commands, like 'ls' etc.
My guess is that compgen behaves a bit different then normal commands. 
For example: whereis compgen returns (terminal): empty, while it is expected to return the location of the binary.

My question is: how to get the output of compgen -c into my node script? My goal is to have a list of all Linux commands.

**Comment by RIAEvangelist** [comment]
Is it possible this is only accessable to your user account and not the system path? This seems the most likely reason for an alias like behavior. Similar to .bashrc or something?
