### ISSUE TITLE
Add get process by Id

### ISSUE THREAD

**Issue by AvdylKrasniqi** [RIAEvangelist/node-cmd#51]
It would be cool if we could directly access any process by a command like 
`
const processRef = cmd.getProcessById(<processid>)`

or 

`const processRef = cmd.getProcessByTitle(<process_title>)`

**Comment by RIAEvangelist** [comment]
I don't understand what you are looking for.

**Comment by RIAEvangelist** [comment]
I don't see how this is related to this module. If you could make a case for it, I would consider. You can do this as it stands in the module by requesting the process via the command passed to `run`.

Closing for now, open to hearing more though.
