### ISSUE TITLE
Example Error?

### ISSUE THREAD

**Issue by atx49559** [RIAEvangelist/node-cmd#53]
Sync stderr:  ${syncDir.stderr} → Sync stderr:  ${**syncData**.stderr}

**Comment by RIAEvangelist** [comment]
(?)

**Comment by antoine-moquereau** [comment]
just seems there is a typo here :
https://github.com/RIAEvangelist/node-cmd/blob/3869d503eb3a6d196f2f541465171a069adddc4d/README.md#L72
;)

**Comment by BarrBrian** [comment]
I see how this happened. The readme uses syncData but the example files use syncDir.

I personally favor the syncDir convention since data is a property on the object listening to the stream, not the data feed itself. 

I'll make a PR updating the readme to fix the typo + match the examples.

**Comment by RIAEvangelist** [comment]
merged the fix in #55
