### ISSUE TITLE
changing directory using node-cmd  not working

### ISSUE THREAD

**Issue by ruchit31** [RIAEvangelist/node-cmd#6]

**Comment by RIAEvangelist** [comment]
remember each command you run is like its own terminal.

so to do multiple commands you might run like this :

``` javascript

cmd.run(
    `
     cd ../
     echo "hello world" >> fakeFile.txt
    `
)


```

**Comment by samthomson** [comment]
@ruchit31 are you on windows? If so you must run commands as one line. See my comment on issue #18
