### ISSUE TITLE
cf commands not working

### ISSUE THREAD

**Issue by koushikramkt** [RIAEvangelist/node-cmd#9]
1. This Works Fine
   cmd.get(
      `cf`, function(data){
          console.log('\nSome Data:\n\n' + data)
      });
2. This Doesn't work 
   cmd.get(
      `cf login`, function(data){
          console.log('\nSome Data:\n\n' + data)
      });

Please let me know if I'm doing something wrong.

**Comment by RIAEvangelist** [comment]
are you sure you have cf installed?

**Comment by RIAEvangelist** [comment]
and that the user you are running it as has access?

IE. do you need root privileges? are you running under a different user? etc.

Just asking.

**Comment by RIAEvangelist** [comment]
no response so closing.
